/**
 * Match commentary strings. Edit this file to add or change lines;
 * use {team} and {player} as placeholders (replaced at runtime).
 * Add new categories here for future event types (e.g. SET_PIECE, PENALTY_AWARDED).
 */

import type { Team, Player } from '@/types/game';

export const COMMENTARY: Record<string, string[]> = {
  ATTACK: [
    "{team} are pouring forward!",
    "A dangerous cross into the box by {player}.",
    "Great footwork by {player} to beat his man.",
    "{player} looks for an opening...",
    "Stunning run from {player}!",
    "{team} are piling on the pressure!",
    "A speculative effort from distance by {player}!",
    "The defense is stretched wide by {team}.",
    "Chaos in the penalty area!",
    "{player} is causing all sorts of problems for the defense.",
    "{player} darts into space for {team}!",
    "Lovely one-two work from {team}!",
    "{player} swings it in with wicked pace!",
    "{player} cuts inside… looking dangerous.",
    "{team} are knocking on the door now!",
    "A teasing ball across the face of goal!",
    "{player} tries to wriggle free in the box!",
    "That's a clever run from {player}!",
    "{player} drives at the back line!",
    "The crowd senses something here…",
    "{team} are turning the screw!",
    "A quick break for {team}!",
    "{player} is in behind…!",
    "A low cross flashed into the area!",
    "{player} shapes to shoot…",
    "{team} overload the flank!",
    "A neat exchange on the edge of the area.",
    "{player} wins the duel and keeps it alive!",
    "{player} looks to pick out a runner.",
    "{team} are attacking with real intent!",
  ],
  MIDFIELD: [
    "{player} controls the tempo in the middle.",
    "{team} are patient with their build-up.",
    "A crunching tackle in midfield by {player}!",
    "{player} sprays the ball out wide.",
    "Battle for possession in the center circle.",
    "{player} wins the ball back for {team}.",
    "Patient passing from {team} in the middle.",
    "A wayward pass from {player} ends that move.",
    "{player} looks to unlock the defense with a through ball.",
    "{team} are moving the ball well across the pitch.",
    "{player} snaps into a challenge and wins it cleanly!",
    "A tidy pass from {player} keeps {team} moving.",
    "{player} holds off the pressure superbly.",
    "{team} recycle possession and go again.",
    "A clever turn from {player} in midfield.",
    "Scrappy battle in the middle — nobody giving an inch.",
    "{player} switches play to stretch the defense.",
    "{player} shows great composure under pressure.",
    "{team} slow it down… then look to accelerate.",
    "{player} clips a pass over the top!",
    "That move breaks down — the midfield line holds firm.",
    "{player} nicks it back and starts the counter!",
    "A heavy touch from {player} invites trouble.",
    "Midfield pressure from {team} is relentless.",
    "{player} is pulling the strings for {team}.",
  ],
  DEFENSE: [
    "{team} are under pressure here.",
    "A vital clearance by {player}!",
    "Solid defending from {team}.",
    "{player} tracks back well to stop the break.",
    "The offside trap works perfectly for {team}!",
    "Desperation defending now from {player}.",
    "{team} are sitting deep, inviting pressure.",
    "A towering header from {player} clears the danger.",
    "{player} intercepts the pass just in time.",
    "The keeper shouts instructions at his back four.",
    "{player} times the tackle perfectly!",
    "Brave defending from {player} — stood his ground.",
    "{team} throw bodies in the way!",
    "A last-ditch block from {player}!",
    "That's excellent positioning from {player}.",
    "{player} reads it early and snuffs it out.",
    "The back line for {team} holds steady.",
    "A nervous moment… but {team} clear their lines.",
    "{player} shepherds it out of danger.",
    "Good tracking back from {player}.",
    "{team} are defending deep and compact.",
    "A needless pass there — invites pressure on {team}.",
    "{player} gets a foot in at just the right time.",
    "A strong header away from {player}.",
    "{player} wins the aerial battle convincingly.",
  ],
  SAVE: [
    "UNBELIEVABLE SAVE BY {player}!",
    "{player} tips it over the bar!",
    "A vital block by the keeper, {player}.",
    "The fans are on their feet after that save from {player}!",
    "Routine catch for {player}.",
    "Sharp reflexes shown there by {player}.",
    "What a stop from {player}!",
    "{player} gets down quickly — brilliant!",
    "That's a strong hand from {player}!",
    "{player} saves it… and holds on!",
    "Parried away by {player}!",
    "{player} stands tall and denies them!",
    "A fingertip save from {player}!",
    "{player} reacts first — superb goalkeeping!",
    "Saved at the near post by {player}!",
    "{player} makes it look easy.",
    "That could've been trouble — {player} dealt with it.",
    "{player} punches clear under pressure!",
  ],
  MISS: [
    "{player} hits the post!",
    "High and wide from {player}. Poor effort.",
    "{player} should have scored there!",
    "Just wide of the upright from {player}!",
    "He's missed a sitter! {player} can't believe it.",
    "Straight at the keeper from {player}.",
    "{player} blazes it over the bar!",
    "That's dragged wide by {player}.",
    "{player} snatches at it — wasted chance.",
    "Never really got hold of it, {player}.",
    "{player} slices it — and it spins away!",
    "Too close to the keeper from {player}.",
    "{player} leans back and it flies over!",
    "He's got to hit the target there — {player} will know it.",
    "A good opening, but {player} can't make it count.",
    "That one won't trouble anyone — poor from {player}.",
  ],
  GOAL: [
    "{player} fires into the bottom corner!",
    "What a strike! {player} smashes it home!",
    "A poacher's goal! {player} taps it in from close range.",
    "Scramble in the box... and {player} pokes it over the line!",
    "{player} rises highest to head into the top corner!",
    "GOAL! {player} finds the net with clinical precision!",
    "The crowd goes wild! {player} has scored for {team}!",
    "{player} slots it home with real composure!",
    "A thunderous finish from {player}!",
    "{player} rounds the keeper… and scores!",
    "It's in! {player} makes no mistake!",
    "{player} steers it into the corner!",
    "A brilliant team move — finished by {player}!",
    "{player} buries it! {team} deserved that!",
    "A scruffy one… but {player} won't care!",
    "The keeper had no chance — {player} rifles it in!",
    "A towering header! {player} powers it home!",
    "Clinical! {player} does exactly what's needed!",
    "That's a real striker's goal from {player}!",
  ],
  FOUL: [
    "A reckless challenge from {player}!",
    "{player} goes into the book for that one.",
    "Nasty tackle by {player}. The referee isn't happy.",
    "{player} is lucky to stay on the pitch after that.",
    "The whistle blows. Foul by {player}.",
    "{player} clatters into him — free kick given.",
    "That's late from {player}.",
    "{player} leaves one on him there.",
    "The referee stops play — foul by {player}.",
    "{player} is walking a tightrope now.",
    "A cynical pull back by {player}.",
    "{player} goes through the back of him — obvious foul.",
    "No complaints — {player} knew what he was doing.",
    "{player} slides in… and gets none of the ball.",
    "{player} protests, but the whistle's already gone.",
  ],
  INJURY: [
    "{player} is down and looks in real pain.",
    "The physio is coming on for {player}.",
    "That looks like a serious one for {player}.",
    "{player} is being carried off the pitch.",
    "{player} stays down… that doesn't look good.",
    "{player} is hobbling — he might not continue.",
    "The bench is looking worried for {player}.",
    "{player} tries to run it off… but he's struggling.",
    "That was a nasty collision — {player} needs treatment.",
    "{player} is receiving attention near the touchline.",
    "{player} is limping badly here.",
    "This could force a change for {team}…",
    "{player} looks shaken after that challenge.",
    "{player} is helped to his feet — still in discomfort.",
  ],
};

export type CommentaryType = keyof typeof COMMENTARY;

export function getCommentary(
  type: CommentaryType,
  team: Team,
  player?: Player
): string {
  const templates = COMMENTARY[type];
  if (!templates || templates.length === 0) return '';
  const template = templates[Math.floor(Math.random() * templates.length)];
  return template
    .replace(/{team}/g, team.name)
    .replace(/{player}/g, player?.name ?? 'A player');
}
